const $=s=>document.querySelector(s),esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const T={aad:['Aadhaar number',1],pan:['PAN',1],bank:['Bank account',1],upi:['UPI ID',1],ifsc:['IFSC code',0],phone:['Phone number',0],email:['Email address',0],health:['Health word',0]};
const RX=[['aad',/(?<!\d)[2-9]\d{3}[ -]?\d{4}[ -]?\d{4}(?!\d)/g],['pan',/\b[A-Z]{5}\d{4}[A-Z]\b/g],['bank',/(?:a\/c|account)[^\d\n]{0,12}(\d{9,18})/gi,1],['upi',/\b[\w.-]{2,}@(?:oksbi|okhdfcbank|okicici|okaxis|ybl|paytm|upi|axl)\b/gi],['ifsc',/\b[A-Z]{4}0[A-Z0-9]{6}\b/g],['phone',/(?:\+91[ -]?)?\b[6-9]\d{4}[ -]?\d{5}\b/g],['email',/\b[\w.+-]+@[\w-]+\.[\w.]+\b/g],['health',/\b(?:HIV|diabet\w*|pregnan\w*|diagnos\w*|prescription|cancer)\b/gi]];
const D=['0123456789','1234067895','2340178956','3401289567','4012395678','5987604321','6598710432','7659821043','8765932104','9876543210'];
const F=[1,5,7,6,2,8,3,0,9,4];let PM=[[0,1,2,3,4,5,6,7,8,9]];for(let i=1;i<8;i++)PM.push(PM[i-1].map(x=>F[x]));
function verhoeff(s){let c=0;[...s].reverse().forEach((d,i)=>c=+D[c][PM[i%8][+d]]);return c===0}
const REASON={aad:['Aadhaar check passes','12 digits, first digit 2–9, and the Aadhaar check digit is correct. We cannot confirm it was issued to anyone.','CHECKSUM_PASS · ISSUER_NOT_CHECKED'],aadx:['Please check this one','It has 12 digits but fails the Aadhaar check digit. It may be an order or reference number.','CHECKSUM_FAIL · REVIEW']};
function detect(t){const out=[];RX.forEach(([ty,re,g])=>{re.lastIndex=0;let m;while(m=re.exec(t)){let s=m.index,raw=m[0];if(g){s=m.index+m[0].lastIndexOf(m[g]);raw=m[g]}const e=s+raw.length;if(!out.some(o=>s<o.end&&e>o.start))out.push({type:ty,start:s,end:e,raw,action:'MASK',decided:false})}});
out.sort((a,b)=>a.start-b.start);out.forEach((o,i)=>{o.id='f_'+String(i+1).padStart(3,'0');let c='FORMAT_ONLY',w='Looks like the right pattern',r='The layout matches, but we cannot confirm it is real or active.',x='FORMAT_MATCH · ISSUER_NOT_CHECKED';
if(o.type=='aad'){const ok=verhoeff(o.raw.replace(/\D/g,''));[w,r,x]=REASON[ok?'aad':'aadx'];c=ok?'VALIDATED':'REVIEW'}
else if(o.type=='upi'){c='VALIDATED';w='Known UPI app name';r='The ending is a known UPI app. We cannot confirm the account works.'}
else if(o.type=='health'){c='REVIEW';w='Please check this one';r='A health-related word. Only you can tell if it is sensitive here.';x='CONTEXT_MATCH · REVIEW'}
o.cls=c;o.why=w;o.reason=r;o.expl=x;const sc=({VALIDATED:1,FORMAT_ONLY:.6,REVIEW:.35})[c];o.band=sc>=.75?'HIGH':sc>=.5?'MEDIUM':'LOW'});return out}
function mask(o){const keep=o.type=='aad'?4:0;let n=0;return [...o.raw].reverse().map(c=>/[A-Za-z0-9]/.test(c)?(n++<keep?c:'X'):c).reverse().join('')}
const tok=o=>'['+T[o.type][0].toUpperCase().replace(/ /g,'_')+']';
const render=o=>o.action=='TOKEN'?tok(o):o.action=='MASK'?mask(o):o.action=='REMOVE'?'':o.raw;
function prot(){let r='',p=0;S.items.forEach(o=>{r+=S.text.slice(p,o.start)+render(o);p=o.end});return r+S.text.slice(p)}
const SAMPLE={doc:"Name: Asha Verma\nAadhaar: 2341 2341 2346\nPAN: ABCDE1234F\nPhone: +91 98765 43210\nUPI: asha@okicici\nOrder number: 999999999998\nEmail: asha.v@example.com\nNote: follow-up for diabetes clinic",
help:"Unknown number: I know where you live. Your Aadhaar 2341 2341 2346 is with me. Call 98765 43210 or I will post your PAN ABCDE1234F everywhere."};
function toast(m){const t=$('#toast');t.textContent=m;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2600)}
function zoom(d){const f=parseFloat(document.documentElement.style.fontSize)||112.5;document.documentElement.style.fontSize=Math.max(100,Math.min(150,f+d*12.5))+'%'}
function docH(){let r='',p=0;S.items.forEach(o=>{const c=o.action=='KEEP'?'k':o.cls=='REVIEW'&&!o.decided?'r':o.action=='KEEP'?'k':'m';r+=esc(S.text.slice(p,o.start))+`<mark class="${c}">${esc(render(o))||'[deleted]'}</mark>`;p=o.end});return r+esc(S.text.slice(p))}
const need=()=>S.items.filter(o=>o.cls=='REVIEW'&&!o.decided);
function cardH(o){const A=S.kind=='text'?[['MASK','Hide'],['TOKEN','Label'],['REMOVE','Delete'],['KEEP','Keep']]:[['MASK','Cover'],['KEEP','Keep']];const rev=o.cls=='REVIEW'&&!o.decided;
return `<div class="it ${rev?'need':''}" id="c_${o.id}"><div class="h"><h3>${T[o.type][0]}</h3><span class="chip ${o.cls=='REVIEW'?'w':o.cls=='VALIDATED'?'g':''}">${o.why}</span></div>
<div class="val"><span id="v_${o.id}">${esc(mask(o))}</span><button onpointerdown="peek('${o.id}')" onpointerup="hideV('${o.id}')" onpointerleave="hideV('${o.id}')" onkeydown="if(event.key==' '||event.key=='Enter'){event.preventDefault();peek('${o.id}')}" onkeyup="hideV('${o.id}')" aria-label="Hold to peek at the real value for up to five seconds">Hold to peek</button></div>
<div class="acts" role="group" aria-label="What to do with this ${T[o.type][0]}">${A.map(([k,l])=>`<button class="${k=='KEEP'?'kp':''}" aria-pressed="${o.action==k&&(o.decided||k!='MASK'||!rev&&o.decided)}" onclick="act('${o.id}','${k}')">${l}</button>`).join('')}</div>
<details><summary>Why was this flagged?</summary><p>${o.reason}</p><p>Rule: ${o.type}.v1 · Class: ${o.cls} · Confidence: ${o.band} · ${o.expl}</p></details></div>`}
function act(id,a){const o=S.items.find(x=>x.id==id);o.action=a;o.decided=true;const y=scrollY;revV();scrollTo(0,y)}
let pk={};function peek(id){const o=S.items.find(x=>x.id==id);$('#v_'+id).textContent=o.raw;clearTimeout(pk[id]);pk[id]=setTimeout(()=>hideV(id),5000)}
function hideV(id){const o=S.items.find(x=>x.id==id),e=$('#v_'+id);if(o&&e)e.textContent=mask(o);clearTimeout(pk[id])}
function check(){const P=prot();const left=detect(P).filter(o=>!/^[\sXx\W]*$/.test(o.raw.split('@')[0]));const leak=S.items.filter(o=>o.action!='KEEP'&&P.replace(/\s/g,'').includes(o.raw.replace(/\s/g,'')));return{P,left,leak,c1:!left.length,c2:!leak.length}}
function receipt(c){const by={};S.items.forEach(o=>{const k=T[o.type][0];by[k]=by[k]||{};by[k][o.action]=(by[k][o.action]||0)+1});const N={MASK:'hidden',TOKEN:'labelled',REMOVE:'deleted',KEEP:'kept visible'};
return `NIRAKSHAN PRIVACY RECEIPT\nRun: ${RID}\nInput: ${S.kind=='text'?'pasted text':S.kind=='png'?'PNG/JPG image':'PDF, '+S.pages.length+' page(s)'}\nFound: ${S.items.length} items\n`+Object.entries(by).map(([k,v])=>`- ${k}: `+Object.entries(v).map(([a,n])=>n+' '+N[a]).join(', ')).join('\n')+`\nChecks: ${c.c1&&c.c2?'2 of 2 text checks passed':'FAILED'}; ${S.kind=='text'?'metadata and QR checks not applicable to plain text':'file rebuilt from pixels (metadata and hidden text removed); QR not checked'}\nResult: ${c.left.length||!c.c2?'Some details still visible':'No detected details remain in the protected copy'}\nNo external upload. Local processing. Volatile session cache: up to 10 minutes.\nTip: for KYC, share a masked Aadhaar where allowed.`}
function dl(){if(S.kind!='text')return dlFile();const c=check();const b=new Blob([c.P],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='shielded_'+Math.random().toString(16).slice(2,10)+'.txt';a.click();toast('Protected copy downloaded')}
function cp(t,m){navigator.clipboard?navigator.clipboard.writeText(t).then(()=>toast(m),()=>toast('Copy was blocked. Please select the text and copy it.')):toast('Copy is not available here')}
function cpt(){cp(check().P,'Protected text copied')}function cpr(){cp(receipt(check()),'Receipt copied')}
const norm=t=>t.replace(/[\u0966-\u096F]/g,c=>c.charCodeAt(0)-0x966).replace(/[\u0660-\u0669]/g,c=>c.charCodeAt(0)-0x660);
let S={page:'home',step:0,text:'',items:[],strict:true,err:'',kind:'text',pages:[],ch:[]},H={},ST=600,RID='run_'+Math.random().toString(16).slice(2,10),idle=true;
const PG=[['home','Home','','Start here'],['shield','Shield Workbench','','Open tool'],['spot','Spot the Leaks','','Play'],['help','Harassment Help','r','Get help'],['showdown','Showdown','','Run demo'],['evidence','Evidence Board','','Run tests'],['files','Files & QR','','See support'],['learn','Learn','','Read']];
const DESC={shield:'Paste text, review each finding, protect it and save with a proof check.',spot:'A short game: tap the details that should never be shared.',help:'A 5-step plan, emergency numbers and a safe copy of the message.',showdown:'Watch a clean export pass and a risky one get blocked.',evidence:'Live precision and recall on a hostile test set, per type.',files:'What photos, PDFs and QR codes need the local server.',learn:'Plain-language how it works, limits and common questions.'};
function nav(){$('#nav').innerHTML=PG.map(([k,l,c])=>`<button class="${c}" onclick="go('${k}')" ${S.page==k?'aria-current="page"':''}>${l}</button>`).join('')}
function go(p){S.page=p;if(p=='shield'&&!S.items.length)S.step=0;draw();scrollTo(0,0)}
function draw(){nav();$('#app').innerHTML=({home:homeV,shield:shieldV,spot:spotV,help:helpV,showdown:showV,evidence:evV,files:filesV,learn:learnV})[S.page]()+pager();gdraw();post()}
function pager(){const i=PG.findIndex(p=>p[0]==S.page),a=PG[i-1],b=PG[i+1];return `<div class="pager"><span>${a?`<button class="btn alt" onclick="go('${a[0]}')">‹ ${a[1]}</button>`:''}</span><span class="lab">Page ${i+1} of ${PG.length}</span><span>${b?`<button class="btn" onclick="go('${b[0]}')">${b[1]} ›</button>`:''}</span></div>`}
function tour(n){if(n==1){S.text=SAMPLE.doc;scan();go('shield')}if(n==2)go('showdown');if(n==3)go('evidence');if(n==4)go('learn')}
function homeV(){return `<div><span class="pill">Demo · made-up data only</span><h1>Look closely before you share</h1>
<p class="lead">Drop a PDF or PNG, or paste text. Nirakshan finds private details, hides them for good, and then checks its own work. No external upload. Everything stays on this device.</p>
<div class="row" style="margin:0 0 30px"><button class="btn go" onclick="T0=Date.now();gd(0)">Start the 3-minute demo</button><button class="btn alt" onclick="go('shield')">Open Shield Workbench</button></div></div>
<div class="lab">PAGES</div><h2>Pick where to go</h2><div class="grid">${PG.slice(1).map(([k,l,c,a])=>`<button class="gw ${c}" onclick="go('${k}')"><h3>${l}</h3><p>${DESC[k]}</p><b>${a} ›</b></button>`).join('')}</div>
<div class="band"><div class="lab">THREE CALM STEPS</div><h2>How a check goes</h2><div class="grid" style="margin-bottom:0">${[['1 Add','Paste your text. It is held in memory only.'],['2 Review','See every detail we found. Hide, label, delete or keep each one.'],['3 Protect','We re-scan the copy, show the result, and give you a receipt with counts only.']].map(([a,b])=>`<div class="card" style="margin:0"><h3>${a}</h3><p style="margin:0">${b}</p></div>`).join('')}</div></div>
<div class="lab">WHAT IT LOOKS FOR</div><h2>Details we can find</h2><p class="lead">Aadhaar, PAN, bank account, UPI ID, IFSC code, phone, email and health words. Each one shows why it was flagged.</p>
<div class="two"><div class="card good"><h3>What Nirakshan does</h3><ul class="p"><li>Hides or deletes what you choose.</li><li>Re-scans the result before you save.</li><li>Blocks saving if a high-risk detail is still visible.</li><li>Clears everything after 10 idle minutes.</li></ul></div>
<div class="card bad"><h3>What it cannot do</h3><ul class="p"><li>Confirm a number is real, issued or active.</li><li>Check names or addresses.</li><li>Read handwriting or blurry photos in this demo.</li><li>Promise complete privacy.</li></ul></div></div>
<div class="card"><h3>Quick questions</h3><details><summary>Is my text sent anywhere?</summary><p>No. Text mode makes no network calls. For PNG and PDF the page fetches open-source PDF and OCR readers once from a public CDN; your file itself never leaves this device.</p></details><details><summary>Can I use it without internet?</summary><p>Text mode works offline. PNG and PDF need internet once so the readers can load. The built-in sample files work offline.</p></details><details><summary>What file types work?</summary><p>Pasted text, PNG/JPG photos and PDFs up to 10 pages. Locked PDFs and QR codes need the local server.</p></details></div>`}
/* SHIELD */
function shieldV(){return stepper()+[addV,revV,saveV][S.step]()}
function stepper(){const L=['Add your text','Review what we found','Protect and save'];return `<div class="steps">${L.map((l,i)=>`<button ${i>0&&!S.items.length?'disabled':''} onclick="S.step=${i};draw()" class="${S.step==i?'on':S.step>i?'ok':''}" ${S.step==i?'aria-current="step"':''}><b>STEP ${i+1} OF 3</b>${l}</button>`).join('')}</div>`}
function addV(){return `<h1>Shield Workbench</h1><p class="lead">Add a PDF or PNG, or paste text. Nothing leaves this device.</p>
<div class="mt"><button class="${S.am!='text'?'on':''}" onclick="S.am='file';draw()">Add PDF / PNG</button><button class="${S.am=='text'?'on':''}" onclick="S.am='text';draw()">Paste text</button></div>${S.am=='text'?'':`<div class="card drop" ondragover="event.preventDefault()" ondrop="event.preventDefault();fileIn(event.dataTransfer.files[0])"><h3>Drop a PDF or PNG here</h3><p style="margin:0">PDF up to 10 pages, or a PNG/JPG photo. Covered boxes are burned into the saved file.</p>
<div class="row"><label class="btn go" for="fi" style="display:inline-flex;align-items:center;cursor:pointer">Choose a file</label><input id="fi" type="file" accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/*" hidden onchange="fileIn(this.files[0])"></div><div id="fs"></div>${S.err?`<div class="box bad" style="margin-top:12px"><b>${S.err}</b></div>`:''}</div>`}${S.am!='text'?'':`<div class="card"><label class="l" for="tx">Paste the text you want to check</label><textarea id="tx" oninput="S.text=this.value;S.err=''">${esc(S.text)}</textarea>${S.err?`<div class="box bad" style="margin-top:12px"><b>${S.err}</b></div>`:''}
<div class="row"><button class="btn" onclick="scan();draw()">Check this text</button><button class="btn alt" onclick="S.text=SAMPLE.doc;S.err='';draw()">Use the made-up example</button></div><p class="note">Photos are read with on-device OCR, so handwriting and blurry photos may be missed. Names and addresses are not checked.</p></div>`}`}
function scan(){S.err='';if(!S.text.trim()){S.err='Please paste some text first.';S.step=0;S.items=[];return}S.text=norm(S.text);if(S.kind!='text'&&S.text!==S.ftxt)S.kind='text';S.items=detect(S.text);S.step=1;S.empty=!S.items.length;if(S.empty)S.step=0;idle=false}
function revV(){const n=S.items.length,hi=S.items.filter(o=>T[o.type][1]).length,nd=need().length;
return `<h1>Review what we found</h1><p class="lead">Every detail is hidden by default. Choose what to do with each one.</p><div class="card"><div class="sum"><div><b>${n} found</b> · ${hi} high-risk · ${n-hi} other${nd?` · <span style="color:var(--am);font-weight:700">${nd} need your check</span>`:''}</div><label class="sw"><input type="checkbox" ${S.strict?'checked':''} onchange="S.strict=this.checked;draw()"> Strict mode</label></div>
<p class="note">${S.strict?'Strict mode is ON. You cannot save a copy that still shows a high-risk detail or has unchecked items.':'Strict mode is OFF. You may keep details visible, but the result will not be called safe.'}</p></div>
<div class="card"><h3>${S.kind=='text'?'Your text, as it will look':'Your file, as it will look'}</h3>${S.kind=='text'?`<div class="doc">${docH()}</div>`:pvH()}</div>${S.items.map(cardH).join('')}<div class="row"><button class="btn alt" onclick="S.step=0;draw()">Back</button><button class="btn go" onclick="S.step=2;draw();scrollTo(0,0)">Continue to protect and save</button></div>`}
function act(id,a){const o=S.items.find(x=>x.id==id);o.action=a;o.decided=true;const y=scrollY;draw();scrollTo(0,y)}
function gate(){const c=check(),fail=!c.c1||!c.c2,nd=need().length,kept=S.items.map((o,i)=>[o,i]).filter(([o])=>o.action=='KEEP'&&T[o.type][1]);let msg='';
if(S.strict&&kept.length)msg=`Export blocked: one identifier is still in the file (row ${kept[0][1]+1}). Fix it or mark it for removal to continue.`;else if(S.strict&&nd)msg=`Please check the ${nd} item${nd>1?'s':''} marked "Please check" before saving.`;else if(S.strict&&fail)msg='Export blocked: a detail is still visible in the protected copy. Go back and hide or delete it.';
return{c,fail,blocked:!!msg,msg,cat:[...new Set(kept.map(([o])=>T[o.type][0]))]}}
function saveV(){const g=gate(),c=g.c,rc=receipt(c);return `<h1>Protect and save</h1><p class="lead">We re-scan the protected copy to make sure nothing slipped through.</p>
${g.blocked?`<div class="box bad" role="alert"><b>Not saved yet</b><p>${g.msg}</p></div><div class="row" style="margin-bottom:16px"><button class="btn" onclick="S.step=1;draw()">Go back and fix it</button></div>`:
`<div class="box ${g.fail?'bad':'ok'}"><b>${g.fail?'Some details are still visible':'2 of 2 text checks passed'}</b><p>${g.fail?'You chose to keep some details. This copy is not fully protected.':`No detected details remain. ${S.kind=='text'?'Metadata and QR checks only apply to images and PDFs.':'The file was rebuilt from pixels, so metadata and any hidden text are gone. QR codes are not checked.'} Names and addresses are not checked.`}</p></div>
<div class="card"><h3>Protected copy</h3>${S.kind=='text'?`<pre>${esc(c.P)}</pre>`:pvH(1)}<div class="row"><button class="btn go" onclick="dl()">Download protected ${S.kind=='text'?'copy':S.kind.toUpperCase()}</button>${S.kind=='text'?'<button class="btn alt" onclick="cpt()">Copy protected text</button>':''}</div></div>`}
<div class="card"><h3>Privacy receipt</h3><p class="note" style="margin:0 0 10px">Counts only. No personal details.</p><pre>${esc(rc)}</pre><div class="row"><button class="btn alt" onclick="cpr()">Copy receipt</button><button class="btn alt" onclick="purge()">Start over and clear everything</button></div></div>`}
function purge(t){S={page:'shield',step:0,text:'',items:[],strict:true,err:'',kind:'text',pages:[],ch:[]};ST=600;idle=true;RID='run_'+Math.random().toString(16).slice(2,10);draw();toast(t||'Everything was cleared');scrollTo(0,0)}
/* SPOT */
const GL=[['Hi Meera, here is the form again.'],['Aadhaar: ',{v:'2341 2341 2346',k:1}],['PAN: ',{v:'ABCDE1234F',k:1}],['Call me on ',{v:'98765 43210',k:1}],['Pay to ',{v:'asha@okicici',k:1}],['Order number: ',{v:'999999999998',k:0}],['Meet at ',{v:'5 pm',k:0},' near the station'],['Photo taken ',{v:'on Sunday',k:0}]];let G={f:{},done:false};
function tg(i,j){if(G.done)return;G.f[i+'-'+j]=!G.f[i+'-'+j];draw()}
function spotV(){let ca=0,fa=0,tot=0;const body=GL.map((l,i)=>`<div style="margin:8px 0">${l.map((p,j)=>{if(typeof p=='string')return esc(p);const f=G.f[i+'-'+j];let c='';if(G.done){c=p.k&&f?'hit':p.k?'miss':f?'fa':'';}if(p.k)tot++;if(f&&p.k)ca++;if(f&&!p.k)fa++;return `<button class="tk ${c}" aria-pressed="${!!f}" onclick="tg(${i},${j})">${esc(p.v)}</button>`}).join('')}</div>`).join('');
const mi=tot-ca;return `<h1>Spot the Leaks</h1><p class="lead">Below is a pretend chat. Tap every detail you would hide before sharing. Then press Check.</p><div class="card"><div class="doc" style="line-height:1.6">${body}</div>
<div class="row"><button class="btn go" onclick="G.done=true;draw()">Check my answers</button><button class="btn alt" onclick="G={f:{},done:false};draw()">Try again</button></div></div>
${G.done?`<div class="box ${mi||fa?'bad':'ok'}"><b>You found ${ca} of ${tot} leaks${fa?` and flagged ${fa} harmless detail${fa>1?'s':''}`:''}</b><p>Green = correct. Red = missed leak. Amber = harmless. The 12-digit order number looks like an Aadhaar number but fails its check digit, so it needs a human look.</p></div>
<div class="row"><button class="btn" onclick="S.text=GL.map(l=>l.map(p=>typeof p=='string'?p:p.v).join('')).join('\\n');scan();go('shield')">Fix them in the Shield</button></div>`:''}`}
/* HELP */
const STEPS=['Do not reply, pay or call back.','Write down the date, time and who sent it. Take screenshots.','Protect your own details: hide them in a copy before you show anyone.','Check Aadhaar and bank activity. UIDAI helpline: 1947. Tell your bank if money is involved.','Report it: call 1930 or visit cybercrime.gov.in. Share only the protected copy.'];
function helpV(){const n=Object.values(H).filter(x=>x===true).length;return `<h1 style="color:var(--rd)">Someone has your details? One step at a time.</h1><p class="lead">You are not at fault. Tick each step when done.</p>
<div class="two"><div class="card todo bad"><h3>Your plan (${n} of 5 done)</h3>${STEPS.map((s,i)=>`<label><input type="checkbox" ${H[i]?'checked':''} onchange="H[${i}]=this.checked;draw()"><span class="${H[i]?'d':''}">${s}</span></label>`).join('')}</div>
<div><div class="card"><h3>Protect the message first</h3><p>Paste the threatening message. We hide your details so you can show it safely.</p><button class="btn red" onclick="S.text=SAMPLE.help;scan();go('shield')">Open the protector</button></div>
<div class="card"><h3>Evidence note</h3><label class="l" for="hs">Where did it come from?</label><input type="text" id="hs" value="${esc(H.s||'')}" oninput="H.s=this.value"><label class="l" for="hd" style="margin-top:10px">Date and time</label><input type="text" id="hd" value="${esc(H.d||'')}" oninput="H.d=this.value"><div class="row"><button class="btn alt" onclick="cp('EVIDENCE NOTE\\nSource: '+(H.s||'not entered')+'\\nDate/time: '+(H.d||'not entered')+'\\nProtected copy attached.','Evidence note copied')">Copy note</button></div></div>
<div class="box bad"><b>In danger right now? Call 112.</b><p>Cyber crime helpline: 1930.</p></div></div></div>`}
/* SHOWDOWN */
let SD={};
function runSD(k){const t=SAMPLE.doc;let it=detect(t);if(k=='bad')it.find(o=>o.type=='aad').action='KEEP';it.forEach(o=>o.decided=true);const o0=[S.text,S.items];S.text=t;S.items=it;const c=check(),g=gate();S.text=o0[0];S.items=o0[1];SD[k]={fail:!c.c1||!c.c2||g.blocked,cat:[...new Set(c.left.map(o=>T[o.type][0]))],n:it.length};SD.rival=detect(t).length;draw()}
function sdCard(k,title,sub){const r=SD[k];return `<div class="card ${k=='bad'?'bad':'good'}"><h3>${title}</h3><p>${sub}</p>${r?`<div class="box ${r.fail?'bad':'ok'}"><b>${r.fail?'FAIL · export blocked':'CLEAN · 2 of 2 text checks passed'}</b><p>${r.fail?`Still visible: ${r.cat.join(', ')||'a kept item'}. No file was returned and Download is disabled.`:`All ${r.n} details hidden. Download is ready (made-up data only).`}</p></div>`:''}<button class="btn ${k=='bad'?'red':'go'}" onclick="runSD('${k}')">Run ${k=='bad'?'hostile':'normal'} test</button></div>`}
function showV(){return `<h1>Showdown</h1><p class="lead">Same made-up document, two runs. The first is done properly. In the second we deliberately keep one Aadhaar number.</p><div class="two">${sdCard('ok','Normal run','Every detail hidden. The proof should pass.')}${sdCard('bad','Hostile run','One Aadhaar number kept. The proof should fail.')}</div>
<div class="card"><h3>Common method: a black box on top</h3><p>${SD.rival?`Covering text with a shape still leaves the words underneath. A re-scan of that file finds <b>${SD.rival} items</b>. Nirakshan removes the text instead.`:'Run a test above to see what a shape-on-top method leaves behind.'}</p><p class="note">Adobe's dedicated Redact tool would also pass a removal test, but you must find every identifier yourself and prove the output.</p></div>`}
/* EVIDENCE */
const FX=[['Devanagari digits','आधार: २३४१ २३४१ २३४६',['aad']],['Leaking black box','Name: ██████ PAN ABCDE1234F',['pan']],['Empty document','',[]],['Decoys and ordinary email','Order 999999999998, mail a.b@example.com, call 98765 43210, pay asha@okicici',['aad','email','phone','upi']]];let EV=null;
function runEV(){const m={};EV=FX.map(([n,t,e])=>{const f=detect(norm(t)).map(o=>o.type);f.concat(e).forEach(k=>m[k]=m[k]||{tp:0,fp:0,fn:0});f.forEach(k=>e.includes(k)?m[k].tp++:m[k].fp++);e.forEach(k=>{if(!f.includes(k))m[k].fn++});return[n,e.length,f.length,e.every(k=>f.includes(k))&&f.length==e.length]});EV.m=m;draw()}
function evV(){return `<h1>Evidence Board</h1><p class="lead">A small hostile set of made-up text. Numbers are calculated live from the real detector, one row per type, never one blended score.</p><div class="row" style="margin:0 0 16px"><button class="btn go" onclick="runEV()">Run the hostile set</button></div>
${EV?`<div class="card"><h3>Results by fixture</h3><table><tr><th>FIXTURE</th><th>EXPECTED</th><th>FOUND</th><th>RESULT</th></tr>${EV.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="chip ${r[3]?'g':'x'}">${r[3]?'Match':'Miss'}</span></td></tr>`).join('')}</table></div>
<div class="card"><h3>Precision and recall by type</h3><table><tr><th>TYPE</th><th>PRECISION</th><th>RECALL</th><th>FALSE ALARMS</th><th>MISSED</th></tr>${Object.entries(EV.m).map(([k,v])=>`<tr><td>${T[k][0]}</td><td>${v.tp+v.fp?Math.round(100*v.tp/(v.tp+v.fp))+'%':'–'}</td><td>${v.tp+v.fn?Math.round(100*v.tp/(v.tp+v.fn))+'%':'–'}</td><td>${v.fp}</td><td>${v.fn}</td></tr>`).join('')}</table></div>`:''}
<div class="card"><h3>Needs the local server</h3><table><tr><td>WhatsApp-compressed screenshot</td><td><span class="chip w">Image engine</span></td></tr><tr><td>Angled card photo</td><td><span class="chip w">Image engine</span></td></tr><tr><td>Locked bank-statement PDF</td><td><span class="chip w">PDF engine</span></td></tr><tr><td>PDF with a leaking black box</td><td><span class="chip w">PDF engine</span></td></tr></table><p class="note">The set is tiny and made up. It shows behaviour, not general accuracy. Names and addresses are never checked.</p></div>`}
/* FILES */
function filesV(){return `<h1>Files and QR</h1><p class="lead">Pasted text, PNG/JPG photos and PDFs (up to 10 pages) work in this demo. Locked PDFs and QR codes need the local Nirakshan server.</p>
<div class="card"><h3>What each input needs</h3><table><tr><td>Pasted text</td><td><span class="chip g">In this demo</span></td></tr><tr><td>PNG or JPG photo (reads the text in the picture)</td><td><span class="chip g">In this demo</span></td></tr><tr><td>PDF up to 10 pages (text or scanned)</td><td><span class="chip g">In this demo</span></td></tr><tr><td>Locked PDF (you type the password here)</td><td><span class="chip w">Local server</span></td></tr><tr><td>QR code on a card</td><td><span class="chip w">Local server · limited</span></td></tr></table>
<div class="row"><button class="btn go" onclick="go('shield')">Open Shield Workbench</button></div></div>
<div class="two"><div class="card"><h3>Messages you may see</h3><ul class="p"><li>We couldn't read this reliably. Upload a clearer photo, or redact the whole page.</li><li>This PDF is locked. Enter its password here. It stays on your device and is never stored.</li><li>This input is out of scope today (handwriting / unsupported script / scan quality). Nothing was redacted.</li></ul></div>
<div class="card"><h3>QR signature labels</h3><ul class="p"><li><b>VERIFIED_FOR_THIS_ARTIFACT</b>: the signature is valid for this presented card or photo. It does not verify identity.</li><li><b>UNVERIFIED</b>: could not be checked.</li><li><b>UNSUPPORTED_AT_CARD</b>: this kind of QR is not supported.</li></ul></div></div>`}
function fileMsg(i){$('#fm').innerHTML=`<div class="box info" style="margin-top:14px"><b>This page cannot read files</b><p>Nothing was read, uploaded or redacted. Use the local server for images and PDFs.</p></div>`;i.value=''}
/* LEARN */
function learnV(){return `<h1>How it works</h1><p class="lead">A short, honest explanation.</p>
<div class="card"><h3>The steps behind a check</h3><ul class="p"><li>Convert Hindi and Arabic-Indic digits to normal digits.</li><li>Find candidate details by their layout.</li><li>Check Aadhaar numbers with their built-in check digit.</li><li>Give each finding a class and a confidence band.</li><li>Hide, label or delete what you choose.</li><li>Re-scan the result before you can save.</li></ul></div>
<div class="card"><h3>What the three labels mean</h3><table><tr><td><span class="chip g">VALIDATED</span></td><td>A tested check and context passed. It still does not prove the item was issued to anyone.</td></tr><tr><td><span class="chip">FORMAT_ONLY</span></td><td>The layout looks right but there is no public way to check it.</td></tr><tr><td><span class="chip w">REVIEW</span></td><td>We are not sure. You decide.</td></tr></table></div>
<div class="two"><div class="card good"><h3>Strict mode (on by default)</h3><p>Blocks saving if an unchecked item, a kept high-risk detail, or a failed proof remains.</p></div><div class="card bad"><h3>We never claim</h3><p>100% accuracy, guaranteed privacy, identity verification, or government approval.</p></div></div>
<div class="card"><h3>Your data</h3><p>Text is held in memory for up to 10 minutes, then cleared. It is never written to disk, logged or sent anywhere. Receipts and file names contain no personal details. The device, clipboard and screen sharing are still outside our control.</p><div class="row"><button class="btn alt" onclick="purge()">Clear everything now</button></div></div>`}
setInterval(()=>{if(idle){$('#tm').textContent='Session: empty';return}ST--;$('#tm').textContent='Clears in '+Math.floor(ST/60)+':'+String(ST%60).padStart(2,'0');if(ST<=0)purge('Session cleared after 10 minutes')},1000);
['click','keydown','input'].forEach(e=>addEventListener(e,()=>ST=600));
/* FILES + GUIDE */
const LIB={pdf:['https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js'],ocr:['https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js']};
async function lib(k,g){if(window[g])return;for(const u of LIB[k]){try{await new Promise((r,j)=>{const s=document.createElement('script');s.src=u;s.onload=r;s.onerror=j;document.head.appendChild(s)});if(window[g])return}catch(e){}}throw Error('offline')}
async function pdfjs(){await lib('pdf','pdfjsLib');if(pdfjs.ok)return;for(const u of LIB.pdf){try{const t=await(await fetch(u.replace('pdf.min','pdf.worker.min'))).text();pdfjsLib.GlobalWorkerOptions.workerSrc=URL.createObjectURL(new Blob([t],{type:'text/javascript'}));pdfjs.ok=1;return}catch(e){}}}
function mk(){return{t:'',ch:[],ly:null,pp:-1,add(s,p,x,y,w,h){const nl=this.pp!=p||this.ly!==null&&Math.abs(y-this.ly)>h/2;this.ly=y;this.pp=p;if(this.t)this.t+=nl?'\n':' ';this.ch.push({s:this.t.length,e:this.t.length+s.length,p,x,y:y-h,w,h});this.t+=s}}}
async function ocr(c,p,R,say){await lib('ocr','Tesseract');say('Reading the text in the image on this device…');const r=await Tesseract.recognize(c,'eng');(r.data.words||[]).forEach(w=>{if(w.text.trim()&&w.confidence>20){const b=w.bbox;R.add(w.text,p,b.x0,b.y1,b.x1-b.x0,b.y1-b.y0)}})}
async function readPDF(buf,R,say){await pdfjs();const d=await pdfjsLib.getDocument({data:buf}).promise,n=Math.min(d.numPages,10),out=[];
for(let p=0;p<n;p++){say(`Reading page ${p+1} of ${n}…`);const pg=await d.getPage(p+1),vp=pg.getViewport({scale:2}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);await pg.render({canvasContext:x,viewport:vp}).promise;
const it=(await pg.getTextContent()).items.filter(i=>i.str.trim());
if(it.length)it.forEach(i=>{const m=pdfjsLib.Util.transform(vp.transform,i.transform),h=Math.hypot(m[2],m[3]);R.add(i.str.trim(),p,m[4],m[5]+h*.2,i.width*2,h*1.2)});else await ocr(c,p,R,say);out.push(c)}
return out}
function load(k,pages,R){S.kind=k;S.pages=pages;S.text=R.t;S.ch=R.ch;S.ftxt=norm(R.t);S.err='';if(!R.t.trim()){S.kind='text';S.pages=[];S.err='No readable text was found in this file. Try a clearer file.';S.items=[];draw();return}scan();draw();scrollTo(0,0)}
async function fileIn(f){if(!f)return;const say=m=>{const e=$('#fs');if(e)e.innerHTML=`<div class="box info" style="margin-top:12px"><b>${m}</b></div>`};const R=mk();
try{if(/pdf/i.test(f.type)||/\.pdf$/i.test(f.name)){say('Reading PDF on this device…');load('pdf',await readPDF(await f.arrayBuffer(),R,say),R)}
else{say('Reading image… the first run loads the OCR reader (needs internet once)');const im=await createImageBitmap(f),k=Math.min(1,2000/im.width),c=document.createElement('canvas');c.width=im.width*k;c.height=im.height*k;c.getContext('2d').drawImage(im,0,0,c.width,c.height);await ocr(c,0,R,say);load('png',[c],R)}}
catch(e){S.err=e.name=='PasswordException'?'This PDF is locked. Locked PDFs need the local server.':e.message=='offline'?'The readers could not load. Check your internet, or use the sample files.':'We could not read this file. Try another one, or use the sample files.';draw()}}
function sample(k){const R=mk(),W=k=='png'?900:1190,H=k=='png'?620:1000,c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);x.fillStyle='#1F5C3F';x.fillRect(0,0,W,70);x.fillStyle='#fff';x.font='bold 32px sans-serif';x.fillText(k=='png'?'KYC FORM (demo)':'BANK STATEMENT (demo)',30,46);x.fillStyle='#1E2420';x.font='30px sans-serif';let y=130;
SAMPLE.doc.split('\n').forEach(l=>{let px=30;l.split(' ').forEach(w=>{const m=x.measureText(w).width;x.fillText(w,px,y);R.add(w,0,px,y+8,m,34);px+=m+x.measureText(' ').width});y+=52});load(k,[c],R)}
function boxes(o){const r=[];S.ch.forEach(c=>{if(c.s<o.end&&c.e>o.start){const n=c.e-c.s,a=Math.max(o.start,c.s)-c.s,b=Math.min(o.end,c.e)-c.s;r.push([c.p,c.x+c.w*a/n-4,c.y-3,c.w*(b-a)/n+8,c.h+6])}});return r}
function paint(p,fin){const s=S.pages[p],c=document.createElement('canvas');c.width=s.width;c.height=s.height;const x=c.getContext('2d');x.drawImage(s,0,0);S.items.forEach(o=>boxes(o).forEach(([q,a,b,w,h])=>{if(q!=p)return;if(o.action=='KEEP'){if(!fin){x.strokeStyle='#B3382C';x.lineWidth=4;x.strokeRect(a,b,w,h)}}else{x.fillStyle='#1E2420';x.fillRect(a,b,w,h)}}));return c}
const pvH=f=>S.pages.map((_,i)=>`<div data-pv="${i}" data-f="${f?1:''}"></div>`).join('');
function post(){document.querySelectorAll('[data-pv]').forEach(h=>{const c=paint(+h.dataset.pv,h.dataset.f);c.style.cssText='width:100%;height:auto;border:1px solid var(--line);border-radius:8px;margin-bottom:10px';h.appendChild(c)})}
function buildPDF(pg){const E=new TextEncoder(),P=[],O=[];let L=0;const w=b=>{if(typeof b=='string')b=E.encode(b);P.push(b);L+=b.length},ob=(n,f)=>{O[n]=L;w(n+' 0 obj\n');f();w('\nendobj\n')};w('%PDF-1.4\n');ob(1,()=>w('<</Type/Catalog/Pages 2 0 R>>'));ob(2,()=>w('<</Type/Pages/Count '+pg.length+'/Kids['+pg.map((_,i)=>(3+3*i)+' 0 R').join(' ')+']>>'));
pg.forEach((p,i)=>{const a=3+3*i,cs=`q ${p.pw} 0 0 ${p.ph} 0 0 cm /Im0 Do Q`;ob(a,()=>w(`<</Type/Page/Parent 2 0 R/MediaBox[0 0 ${p.pw} ${p.ph}]/Resources<</XObject<</Im0 ${a+2} 0 R>>>>/Contents ${a+1} 0 R>>`));ob(a+1,()=>w(`<</Length ${cs.length}>>\nstream\n${cs}\nendstream`));ob(a+2,()=>{w(`<</Type/XObject/Subtype/Image/Width ${p.iw}/Height ${p.ih}/ColorSpace/DeviceRGB/BitsPerComponent 8/Filter/DCTDecode/Length ${p.jpg.length}>>\nstream\n`);w(p.jpg);w('\nendstream')})});
const N=3+3*pg.length,xr=L;w(`xref\n0 ${N}\n0000000000 65535 f \n`);for(let n=1;n<N;n++)w(String(O[n]).padStart(10,'0')+' 00000 n \n');w(`trailer\n<</Size ${N}/Root 1 0 R>>\nstartxref\n${xr}\n%%EOF`);return new Blob(P,{type:'application/pdf'})}
async function dlFile(){const cs=S.pages.map((_,i)=>paint(i,1)),png=S.kind=='png';let b;if(png)b=await new Promise(r=>cs[0].toBlob(r,'image/png'));else{const pg=[];for(const c of cs){const j=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));pg.push({jpg:new Uint8Array(await j.arrayBuffer()),iw:c.width,ih:c.height,pw:c.width/2,ph:c.height/2})}b=buildPDF(pg)}
const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='shielded_'+Math.random().toString(16).slice(2,10)+(png?'.png':'.pdf');a.click();toast('Protected file downloaded')}
/* 3-minute guide */
const GS=[['1 Upload','0:00','Drop a PDF or PNG. Say: nothing leaves this device.'],['2 Review','0:50','Each finding is explained. Cover or keep each one.'],['3 Save','1:30','Re-scan, proof check, receipt. Download the clean file.'],['4 Break it','2:00','Keep one Aadhaar on purpose. The export is blocked.'],['5 Prove it','2:30','Live precision and recall. Then state the limits.']];
const gi=()=>S.page=='shield'?S.step:S.page=='showdown'?3:S.page=='evidence'?4:-1;
function gd(i){if(i<3){S.step=S.items.length?i:0;go('shield')}else go(i==3?'showdown':'evidence')}
function gdraw(){const k=gi();$('#gd').innerHTML='<b class="mono">3-min demo</b>'+GS.map((g,i)=>`<button class="${i==k?'on':''}" onclick="gd(${i})">${g[0]} <small>${g[1]}</small></button>`).join('')+'<button class="tm" onclick="T0=T0?0:Date.now();tk()"><span id="gt">Start timer</span></button>'+(k>=0?`<span class="say">${GS[k][2]}</span>`:'');tk()}
let T0=0;function tk(){const e=$('#gt');if(!e)return;if(!T0){e.textContent='Start 3:00 timer';return}const s=Math.max(0,180-Math.floor((Date.now()-T0)/1000));e.textContent='⏱ '+Math.floor(s/60)+':'+String(s%60).padStart(2,'0')+' left'}
setInterval(tk,500);

draw();
